apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: notification-service
profiles:
  - name: local
    build:
      googleCloudBuild:
        projectId: cwb07-shared-services-7b30
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-west1-docker.pkg.dev/cwb07-shared-services-7b30/application/cwb07-notification-service
          jib:
            type: gradle
            project: service
    deploy:
      helm:
        releases:
          - name: cwb07-notification-service
            createNamespace: true
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}@{{.IMAGE_DIGEST_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}"
            setValues:
              environment: local
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/local.yaml
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      artifacts:
        - image: notification-service
          jib:
            type: gradle
            project: service
    manifests:
      helm:
        releases:
          - name: notification-service
            createNamespace: true
            chartPath: helm/application
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/local.yaml
            setValues:
              environment: local
              net.readinessProbe.initialDelaySeconds: 60
              pullPolicy: IfNotPresent
              postgres.enabled: "true"
              ingress.enabled: "true"
            setValueTemplates:
              image.repository: notification-service
              image.tag: notification-service
    deploy:
      statusCheckDeadlineSeconds: 60
      tolerateFailuresUntilDeadline: true
      helm: {}
    portForward:
      - resourceType: service
        resourceName: notification-service
        namespace: cwb07
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: notification-service-postgres
        namespace: cwb07
        port: 5432
        localPort: 5438
  - name: dev
    build:
      googleCloudBuild:
        projectId: cwb07-shared-services-7b30
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-west1-docker.pkg.dev/cwb07-shared-services-7b30/application/cwb07-notification-service
          jib:
            type: gradle
            project: service
    deploy:
      helm:
        releases:
          - name: cwb07-notification-service
            createNamespace: true
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}@{{.IMAGE_DIGEST_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}"
            setValues:
              environment: dev
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/dev.yaml
  - name: prod
    build:
      googleCloudBuild:
        projectId: cwb07-shared-services-7b30
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-west1-docker.pkg.dev/cwb07-shared-services-7b30/application/cwb07-notification-service
          jib:
            type: gradle
            project: service
    deploy:
      helm:
        releases:
          - name: cwb07-notification-service
            createNamespace: true
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}@{{.IMAGE_DIGEST_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_notification_service}}"
            setValues:
              environment: prod
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/prod.yaml
